### ISSUE TITLE
Question on Synthia-seq dataset

### ISSUE THREAD

**Issue by xyIsHere** [Dayan-Guan/DA-VSN#4]
Dear authors,

Thank you for your great work. I have several questions about the synthia-seq->cityscape-seq adaptation.
The first one is about the scale of training data. It seems like compared with the VIPER dataset, synthia-seq only contains one labeled video with 850 frames in total. Is that true? 
And the second question is that 11 classes are reported the Table 4, but in the dataloader of synthia-seq, 12 classes are used. So, I'm not sure whether the fence class is considered during adaptation or not. 
https://github.com/Dayan-Guan/DA-VSN/blob/d110ff70dacec4156a3787eb49e7f2448dfb91a5/davsn/dataset/SynthiaSeq.py#L11

Thanks in advance for your help!

**Comment by Dayan-Guan** [comment]
Hi @xyIsHere, thank you for your interest in our work!
For the first question, we only use the 850 frames.
For the second question, we use 12 classes for training and only evaluate on 11 classes. Because very few frames contain the 'fence' class, and all the methods can only obtain ~0 IoU on this class.

**Comment by xyIsHere** [comment]
Thank you for your quick clarification. I really appreciate it:P

**Comment by Dayan-Guan** [comment]
Hi @xyIsHere , the code of TPS [ECCV 2022] is available [here](https://github.com/xing0047/TPS). TPS is 3x faster than DA-VSN during training and notably surpasses DA-VSN during testing.
